// module Slope: {
//   let inputs: array<array<Js.String2.t>>
//   type width
//   type height
//   type direction
//   let countTrees: (direction, array<array<string>>) => int
// }

// open Slope

// let solution: (direction, array<array<string>>) => int
// let solution2: (array<direction>, array<array<string>>) => int

// module Tobbogan: {
//   type height
//   type width

//   type direction = (height, width)
// }

